on:
  workflow_call:

jobs:
  check:
    name: "cargo check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run check
        run: make rust-check
